import * as THREE from 'three';import{ASSET,bakeStatic}from'../assetlib.js';
const scene=new THREE.Scene();scene.background=new THREE.Color(0xb5c7ba);scene.fog=new THREE.FogExp2(0x9fb8aa,.021);const camera=new THREE.PerspectiveCamera(54,innerWidth/innerHeight,.1,240);const renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});renderer.setSize(innerWidth,innerHeight);renderer.setPixelRatio(Math.min(devicePixelRatio,1.6));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.18;document.body.prepend(renderer.domElement);
scene.add(new THREE.HemisphereLight(0xddebdc,0x28413a,2.2));const sun=new THREE.DirectionalLight(0xffe1a6,4);sun.position.set(-10,22,-8);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);sun.shadow.camera.left=-28;sun.shadow.camera.right=28;sun.shadow.camera.top=28;sun.shadow.camera.bottom=-28;scene.add(sun);
const waterUniforms={time:{value:0},hero:{value:new THREE.Vector2()},wake:{value:0}};const water=new THREE.Mesh(new THREE.PlaneGeometry(110,110,180,180),new THREE.ShaderMaterial({transparent:true,depthWrite:true,uniforms:waterUniforms,vertexShader:`uniform float time;uniform vec2 hero;uniform float wake;varying vec3 wpos;varying float crest;void main(){vec3 p=position;vec2 q=p.xy;float d=length(q-hero);float ripple=sin(d*5.5-time*7.)*exp(-d*.36)*wake;float broad=sin(q.x*.55+time)*.06+sin(q.y*.7-time*.8)*.045;p.z+=broad+ripple*.12;crest=ripple;wpos=(modelMatrix*vec4(p,1.)).xyz;gl_Position=projectionMatrix*modelViewMatrix*vec4(p,1.);}`,fragmentShader:`uniform float time;varying vec3 wpos;varying float crest;void main(){vec3 deep=vec3(.055,.20,.20),glint=vec3(.56,.83,.74);float bands=.5+.5*sin(wpos.x*1.8+wpos.z*2.1+time*1.2);float fres=pow(1.-abs(dot(normalize(cameraPosition-wpos),vec3(0.,1.,0.))),2.);vec3 col=mix(deep,glint,.12+fres*.43+bands*.055+max(crest,0.)*.45);gl_FragColor=vec4(col,.88);}` ,side:THREE.DoubleSide}));water.rotation.x=-Math.PI/2;water.position.y=0;water.receiveShadow=true;scene.add(water);
water.scale.set(1.45,4,1);
const groundMat=new THREE.MeshStandardMaterial({color:0x344c3c,roughness:.96});groundMat.name='ground';const islands=[];for(const [x,z,s]of[[-10,-9,6],[12,13,8],[-17,18,7],[22,-16,9]]){const m=new THREE.Mesh(new THREE.CylinderGeometry(s*.7,s,1.4,16),groundMat);m.position.set(x,-.45,z);m.receiveShadow=true;scene.add(m);islands.push(m)}
const placements=[[-1,-1,2.9],[2.6,-4,2.4],[-2.3,-7,2.7],[1.2,-10.4,2.3],[-3.3,-13.5,2.8],[.5,-17,2.5],[4,-20,3.0],[1,-24,2.6],[-2,-28,3.1],[2,-32,2.6]];const pads=[];for(const [x,z,s]of placements){const p=await ASSET('./assets/lotus_leaf.js',{height:.28});p.position.set(x,.06,z);p.scale.setScalar(s/2.7);p.rotation.y=Math.random()*6.28;scene.add(p);pads.push({x,z,r:s*.43});}
for(let z=-40;z>-205;z-=7){for(const lane of[-1,0,1]){const x=lane*8+Math.sin(z*.37+lane)*4,s=1.8+((Math.sin(z*1.7+lane)+1)*.55);const p=await ASSET('./assets/lotus_leaf.js',{height:.28});p.position.set(x,.04,z);p.scale.setScalar(s/2.7);p.rotation.y=z+lane;scene.add(p);pads.push({x,z,r:s*.43})}}
for(const [x,z]of[[-6,-4],[7,-12],[-8,-20],[9,-28]]){const b=await ASSET('./assets/bamboo_cluster.js',{height:5});b.position.set(x,0,z);scene.add(b)}for(const [x,z]of[[-5,-7],[6,-17],[-6,-27]]){const l=await ASSET('./assets/stone_lantern.js',{height:2.4});l.position.set(x,.05,z);scene.add(l);const light=new THREE.PointLight(0xf4c56a,10,9,2);light.position.set(x,2,z);scene.add(light)}const gate=await ASSET('./assets/shrine_gate.js',{height:7});gate.position.set(0,.02,-38);scene.add(gate);
for(let z=-42;z>-205;z-=16){for(const side of[-1,1]){const b=await ASSET('./assets/bamboo_cluster.js',{height:4.5+((z*side)%3+3)%3*.4});b.position.set(side*(13+Math.sin(z)*3),0,z);b.rotation.y=z;scene.add(b)}}for(const z of[-62,-94,-126,-158,-190]){const l=await ASSET('./assets/stone_lantern.js',{height:2.4});l.position.set(Math.sin(z)*9,.04,z);scene.add(l);const light=new THREE.PointLight(0xf4c56a,7,7,2);light.position.set(l.position.x,2,z);scene.add(light)}for(const z of[-104,-174]){const g2=await ASSET('./assets/shrine_gate.js',{height:7});g2.position.set(Math.sin(z)*4,.02,z);scene.add(g2)}
for(let z=-35;z>-225;z-=42){for(const side of[-1,1]){const m=await ASSET('./assets/mountain_spire.js',{height:18+((Math.abs(z)+side)%9)});m.position.set(side*(32+Math.abs(Math.sin(z))*12),-.7,z-18);m.rotation.y=z*.2;scene.add(m)}}
const hero=await ASSET('./assets/forest_guardian.js',{height:1.25,keepHierarchy:true});scene.add(hero);hero.position.set(-1,.22,2.9);const joints=hero.userData.joints||{};
const sparks=[];for(let i=1;i<placements.length;i+=2){const [x,z]=placements[i];const m=new THREE.Mesh(new THREE.IcosahedronGeometry(.14,1),new THREE.MeshStandardMaterial({color:0xffe27b,emissive:0xffc64d,emissiveIntensity:4}));m.position.set(x,1,z);scene.add(m);sparks.push(m)}
const rings=[];const ringMat=new THREE.MeshBasicMaterial({color:0xbcebd6,transparent:true,opacity:.8,side:THREE.DoubleSide,depthWrite:false});function splash(big=false){for(let k=0;k<(big?3:1);k++){const r=new THREE.Mesh(new THREE.RingGeometry(.65,.72,48),ringMat.clone());r.rotation.x=-Math.PI/2;r.position.set(hero.position.x,.055+k*.012,hero.position.z);r.userData.life=0;r.userData.speed=big?4.2:2.6;scene.add(r);rings.push(r)}for(let i=0;i<(big?18:6);i++){const d=new THREE.Mesh(new THREE.SphereGeometry(.035,5,4),new THREE.MeshBasicMaterial({color:0xc9eee0,transparent:true}));d.position.copy(hero.position);d.position.y=.18;const a=Math.random()*6.28,sp=(big?.8:.35)+Math.random()*.6;d.userData.vel=new THREE.Vector3(Math.cos(a)*sp,1+Math.random()*1.8,Math.sin(a)*sp);d.userData.life=0;scene.add(d);rings.push(d)}}
const keys={};addEventListener('keydown',e=>{keys[e.code]=true;if(e.code==='Space')jump()});addEventListener('keyup',e=>keys[e.code]=false);document.getElementById('jump').onclick=jump;let playing=false,vy=0,onGround=true,score=0,lastSplash=0;function jump(){if(onGround&&playing){vy=5.3;onGround=false;splash(true)}}document.getElementById('begin').onclick=()=>{playing=true;document.getElementById('start').classList.add('hide')};window.__START__=()=>document.getElementById('begin').click();window.__READY__=true;
let prev=performance.now(),frames=0,fps=60,fpst=prev;const clock=new THREE.Clock();function animate(now){requestAnimationFrame(animate);const real=(now-prev)/1000;prev=now;const dt=Math.min(real,.033),t=clock.getElapsedTime();frames++;if(now-fpst>500){fps=frames/((now-fpst)/1000);frames=0;fpst=now}if(playing){let dx=(keys.KeyD||keys.ArrowRight?1:0)-(keys.KeyA||keys.ArrowLeft?1:0),dz=(keys.KeyS||keys.ArrowDown?1:0)-(keys.KeyW||keys.ArrowUp?1:0);const len=Math.hypot(dx,dz)||1;dx/=len;dz/=len;const speed=4.2;hero.position.x+=dx*speed*dt;hero.position.z+=dz*speed*dt;if(dx||dz)hero.rotation.y=Math.atan2(dx,dz);vy-=11*dt;hero.position.y+=vy*dt;let floor=.12;for(const p of pads)if(Math.hypot(hero.position.x-p.x,hero.position.z-p.z)<p.r)floor=.3;if(hero.position.y<=floor){if(!onGround&&vy<-.8)splash(true);hero.position.y=floor;vy=0;onGround=true}else onGround=false;if((dx||dz)&&floor<.2&&now-lastSplash>190){splash(false);lastSplash=now}waterUniforms.hero.value.set(hero.position.x,-hero.position.z);waterUniforms.wake.value=(dx||dz)&&floor<.2?1:0;for(const s of sparks){if(s.visible&&hero.position.distanceTo(s.position)<1.1){s.visible=false;score++;document.getElementById('score').textContent=score;splash(true)}s.rotation.y+=dt*2;s.position.y=1+Math.sin(t*3+s.id)*.15}const gait=Math.sin(t*10)*.45;if(joints.leftLeg){joints.leftLeg.rotation.x=gait;joints.rightLeg.rotation.x=-gait;joints.leftArm.rotation.x=-gait*.7;joints.rightArm.rotation.x=gait*.7}}
waterUniforms.hero.value.set(hero.position.x/1.45,-hero.position.z/4);waterUniforms.time.value=t;for(let i=rings.length-1;i>=0;i--){const r=rings[i];r.userData.life+=dt;if(r.geometry.type==='RingGeometry'){r.scale.setScalar(1+r.userData.life*r.userData.speed);r.material.opacity=Math.max(0,.8-r.userData.life*.7)}else{r.userData.vel.y-=5*dt;r.position.addScaledVector(r.userData.vel,dt);r.material.opacity=Math.max(0,1-r.userData.life)}if(r.userData.life>1.15){scene.remove(r);rings.splice(i,1)}}const target=new THREE.Vector3(hero.position.x,hero.position.y+3.1,hero.position.z+6.8);camera.position.lerp(target,1-Math.exp(-dt*5));camera.lookAt(hero.position.x,hero.position.y+.55,hero.position.z-3.5);renderer.render(scene,camera);window.__GAME__={fps,frame:Math.round(t*60),speed:playing?4.2:0,pos:[hero.position.x,hero.position.z],score,over:false,draws:renderer.info.render.calls,tris:renderer.info.render.triangles}}requestAnimationFrame(animate);addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});
